name: Update RSS Feeds

on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repo
      uses: action/checkout@main

    - name: Setup node.js
      uses: actions/setup-node@master
    - name: Install dependencies
      run: npm ci
    - name: Generate feeds
      run: node index.js
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public